INSERT INTO patient
(name, birth_date, email, gender, blood_group_type, created_date)VALUES
('Vikram Mehta', '1985-04-17', 'vikram.mehta01@gmail.com', 'MALE', 'A_POSITIVE', NOW()),
('Sneha Kapoor', '1993-09-28', 'sneha.kapoor02@gmail.com', 'FEMALE', 'B_NEGATIVE', NOW()),
('Aditya Bose', '1990-12-05', 'aditya.bose03@gmail.com', 'MALE', 'O_POSITIVE', NOW()),
('Meera Nair', '1997-06-19', 'meera.nair04@gmail.com', 'FEMALE', 'AB_POSITIVE', NOW()),
('Kunal Agarwal', '1988-02-23', 'kunal.agarwal05@gmail.com', 'MALE', 'A_NEGATIVE', NOW()),
('Riya Malhotra', '2000-11-14', 'riya.malhotra06@gmail.com', 'FEMALE', 'O_NEGATIVE', NOW()),
('Soham Das', '1995-07-31', 'soham.das07@gmail.com', 'MALE', 'B_POSITIVE', NOW()),
('Nikita Sinha', '1992-03-08', 'nikita.sinha08@gmail.com', 'FEMALE', 'AB_NEGATIVE', NOW()),
('Rajiv Khanna', '1982-10-26', 'rajiv.khanna09@gmail.com', 'MALE', 'O_POSITIVE', NOW()),
('Tanisha Roy', '1999-01-12', 'tanisha.roy10@gmail.com', 'FEMALE', 'A_POSITIVE', NOW()),
('Manish Tiwari', '1987-08-03', 'manish.tiwari11@gmail.com', 'MALE', 'B_NEGATIVE', NOW()),
('Ira Mukherjee', '2001-05-21', 'ira.mukherjee12@gmail.com', 'FEMALE', 'AB_POSITIVE', NOW()),
('Dev Mallick', '1994-11-07', 'dev.mallick13@gmail.com', 'MALE', 'A_NEGATIVE', NOW()),
('Sanjana Iyer', '1996-04-29', 'sanjana.iyer14@gmail.com', 'FEMALE', 'O_NEGATIVE', NOW()),
('Rahul Bhatia', '1989-09-16', 'rahul.bhatia15@gmail.com', 'MALE', 'B_POSITIVE', NOW()),
('Mitali Sen', '1998-12-22', 'mitali.sen16@gmail.com', 'FEMALE', 'AB_NEGATIVE', NOW()),
('Arnav Joshi', '2002-02-11', 'arnav.joshi17@gmail.com', 'MALE', 'O_POSITIVE', NOW()),
('Kavya Menon', '1991-07-06', 'kavya.menon18@gmail.com', 'FEMALE', 'A_POSITIVE', NOW()),
('Yash Verma', '1986-05-15', 'yash.verma19@gmail.com', 'MALE', 'B_NEGATIVE', NOW()),
('Aditi Choudhury', '1995-10-30', 'aditi.choudhury20@gmail.com', 'FEMALE', 'AB_POSITIVE', NOW()),
('Rishabh Jain', '1993-02-18', 'rishabh.jain21@gmail.com', 'MALE', 'O_NEGATIVE', NOW()),
('Poulomi Ghosh', '1999-08-24', 'poulomi.ghosh22@gmail.com', 'FEMALE', 'A_NEGATIVE', NOW()),
('Nikhil Rao', '1984-06-09', 'nikhil.rao23@gmail.com', 'MALE', 'B_POSITIVE', NOW()),
('Srishti Pandey', '2000-03-27', 'srishti.pandey24@gmail.com', 'FEMALE', 'AB_NEGATIVE', NOW()),
('Varun Chatterjee', '1990-11-19', 'varun.chatterjee25@gmail.com', 'MALE', 'O_POSITIVE', NOW());


INSERT INTO doctor (name, specialization, email) VALUES
('Dr. Arindam Sen', 'Cardiology', 'arindam.sen@hospital.com'),
('Dr. Priya Mukherjee', 'Neurology', 'priya.mukherjee@hospital.com'),
('Dr. Rohan Chatterjee', 'Orthopedics', 'rohan.chatterjee@hospital.com'),
('Dr. Ananya Roy', 'Dermatology', 'ananya.roy@hospital.com'),
('Dr. Sagnik Ghosh', 'Pediatrics', 'sagnik.ghosh@hospital.com'),
('Dr. Ishita Banerjee', 'Gynecology', 'ishita.banerjee@hospital.com'),
('Dr. Abhishek Das', 'General Medicine', 'abhishek.das@hospital.com'),
('Dr. Madhurima Paul', 'Ophthalmology', 'madhurima.paul@hospital.com'),
('Dr. Tanmoy Basu', 'ENT', 'tanmoy.basu@hospital.com'),
('Dr. Nandini Mitra', 'Psychiatry', 'nandini.mitra@hospital.com'),
('Dr. Debojyoti Kar', 'Pulmonology', 'debojyoti.kar@hospital.com'),
('Dr. Pallabi Dutta', 'Endocrinology', 'pallabi.dutta@hospital.com'),
('Dr. Ritwik Ganguly', 'Gastroenterology', 'ritwik.ganguly@hospital.com'),
('Dr. Shraboni Hazra', 'Nephrology', 'shraboni.hazra@hospital.com'),
('Dr. Ayan Nandi', 'Urology', 'ayan.nandi@hospital.com'),
('Dr. Trisha Datta', 'Oncology', 'trisha.datta@hospital.com'),
('Dr. Kabir Bhattacharya', 'Rheumatology', 'kabir.bhattacharya@hospital.com'),
('Dr. Koel Chatterjee', 'Radiology', 'koel.chatterjee@hospital.com'),
('Dr. Prithwish Nandi', 'Anesthesiology', 'prithwish.nandi@hospital.com'),
('Dr. Riya Majumdar', 'Emergency Medicine', 'riya.majumdar@hospital.com'),
('Dr. Soumyajit Roy', 'Cardiology', 'soumyajit.roy@hospital.com'),
('Dr. Meera Kapoor', 'Neurology', 'meera.kapoor@hospital.com'),
('Dr. Vikram Mehta', 'Orthopedics', 'vikram.mehta@hospital.com'),
('Dr. Sneha Saha', 'Dermatology', 'sneha.saha@hospital.com'),
('Dr. Kunal Bose', 'General Surgery', 'kunal.bose@hospital.com');